### ISSUE TITLE
Originally 842996746958245888, after response.json () processing, into 842996746958245800

### ISSUE THREAD

**Issue by lihua123569** [jaydson/es7-async#3]
const data = await response.json();
long    842996746958245888
string  842996746958245800

"records":[{"id":842996746958245888,"name":"玩儿","age":23,"testType":3,"role":null,"phone":null}

Originally 842996746958245888, after response.json () processing, into 842996746958245800

**Comment by jaydson** [comment]
Hi @lihua123569, I don't get it what you mean with this issue.
Can you explain?
